# Generated by Django 3.1.3 on 2021-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('key', models.CharField(max_length=8, unique=True)),
                ('user_id', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
