version: '3.7'

services:
  web:
    build: ./web
#    command.md: python manage.py runserver 0.0.0.0:8000
    command: gunicorn bitly.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
#    volumes:
#      - .:/usr/src/app/
#    ports:
#      - 8000:8000
    expose:
      - 8000
    links:
      - db:db
      - redis:redis
    env_file:
      - web/app/.env.dev
    depends_on:
      - redis
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

  redis:
    build: ./redis
    restart: always
    expose:
      - "6379"

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'bitly'
      MYSQL_USER: 'bitly'
      MYSQL_HOST: 'localhost'
      MYSQL_PASSWORD: 'pass_bitly'
      MYSQL_ROOT_PASSWORD: 'pass_bitly'
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  static_volume:
