version: '3.7'

services:
  web:
    build: ./web
    command: python manage.py test
#    command: gunicorn bitly.wsgi:application -w 5 --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    links:
      - db:db
      - redis:redis
    env_file:
      - web/app/.env.dev
    volumes:
      - ./log:/usr/src/app/log
    depends_on:
      - redis
      - db

  redis:
    build: ./redis
    restart: always
    expose:
      - 6379

  db:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: 'bitly'
      MYSQL_USER: 'bitly'
      MYSQL_HOST: 'localhost'
      MYSQL_PASSWORD: 'pass_bitly'
      MYSQL_ROOT_PASSWORD: 'pass_bitly'
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  static_volume:
